name: learning_notes
description: A new Flutter project.

version: 1.0.0+1

# *******************************************************
# Sometimes running Packages Get here won't finish the job.
# If when you try to start the app, a message appears above
# your dart file saying that pubspec has changed, then hit the
# stop button and then use THAT link to get packages.
# If this starts happening regularly, just run your app
# by hitting the start triangle and then being ready to stop
# right away and run get from there. ** Running Packages upgrade
# doesn't help with this issue.
# *******************************************************

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

# *******************************************************
# You do NOT need to specify each asset individually.
# You can define a folder and everything within it will be
# available.
# *******************************************************

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/svg/


  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

